INFO:werkzeug: * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
INFO:werkzeug:172.17.0.1 - - [12/Sep/2020 07:20:30] "[37mOPTIONS /mindmap HTTP/1.1[0m" 200 -
INFO:root:Traceback (most recent call last):
  File "start.py", line 121, in GetMindmapCases
    postData = json.loads(request.form['mindMapData'])['data']
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/datastructures.py", line 442, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.

INFO:werkzeug:172.17.0.1 - - [12/Sep/2020 07:20:30] "[37mPOST /mindmap HTTP/1.1[0m" 200 -
INFO:werkzeug:172.17.0.1 - - [12/Sep/2020 07:20:38] "[37mOPTIONS /mindmap HTTP/1.1[0m" 200 -
INFO:root:Traceback (most recent call last):
  File "start.py", line 121, in GetMindmapCases
    postData = json.loads(request.form['mindMapData'])['data']
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/datastructures.py", line 442, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.

INFO:werkzeug:172.17.0.1 - - [12/Sep/2020 07:20:38] "[37mPOST /mindmap HTTP/1.1[0m" 200 -
INFO:werkzeug:172.17.0.1 - - [12/Sep/2020 07:21:14] "[37mOPTIONS /mindmap HTTP/1.1[0m" 200 -
INFO:root:Traceback (most recent call last):
  File "start.py", line 121, in GetMindmapCases
    postData = json.loads(request.form['mindMapData'])['data']
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/datastructures.py", line 442, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.

INFO:werkzeug:172.17.0.1 - - [12/Sep/2020 07:21:14] "[37mPOST /mindmap HTTP/1.1[0m" 200 -
